-- Create roles table
CREATE TABLE IF NOT EXISTS public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL CHECK (type IN ('rotational', 'support', 'both')),
    "order" INTEGER DEFAULT 0
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;

-- Create policy to allow read access for all users (public read)
CREATE POLICY "Enable read access for all users" ON public.roles
    FOR SELECT USING (true);

-- Seed initial data
INSERT INTO public.roles (name, type, "order")
VALUES
    ('감독', 'both', 10),
    ('부감독', 'both', 20),
    ('영상', 'both', 30),
    ('조원', 'rotational', 40),
    ('관리', 'support', 10),
    ('기술스텝', 'support', 20),
    ('시스템관리', 'support', 30)
ON CONFLICT (name) DO UPDATE SET
    type = EXCLUDED.type,
    "order" = EXCLUDED."order";
